# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Kubernetes & Cloud Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Tips, tricks, and thoughts on Kubernetes, cloud computing, and more.
baseurl: "" # the subpath of your site, e.g. /blog. For GitHub Pages project sites, set this to '/project-name'.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: YOUR_GITHUB_USERNAME # Replace with your GitHub username

# Build settings
theme: jekyll-theme-chirpy # Replaced Minima with Chirpy
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Chirpy theme settings
lang: en # The lang attribute for <html>
timezone: America/New_York # e.g., America/New_York, Europe/Berlin, Asia/Shanghai
title_template: "%s | %s" # "%s | <site.title>"
description_template: "%s" # "<page.description> | <site.description>"

avatar: /assets/images/.gitkeep # Replace with path to your avatar image, e.g., /assets/img/avatar.png or a remote URL

# The CDN host of Chirpy's static assets.
# See: https://github.com/cotes2020/chirpy-static-assets
img_cdn: "https://cdn.jsdelivr.net/gh/cotes2020/chirpy-static-assets@6/assets/img"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections (e.g., for E-books or other content types)
collections:
  ebooks:
    output: true
    permalink: /ebooks/:path/

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name" # Default author for posts
  - scope:
      path: ""
      type: "ebooks" # Default layout for ebooks if you create an "ebook" layout
    values:
      layout: "page" # Or a custom "ebook" layout if you make one
